version: '3.9'
services:
  rev-proxy:
      build: ./rev-proxy
      ports:
        - "80:80"
  frontend: 
    build: ./tlr-ui
    environment:
      - PORT=3000
    ports: 
    - "3000:3000"
    volumes:
      - ./tlr-ui/:/app
      - /app/node_modules
  api:
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=los-angeles
    ports: 
      - "8000:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app
  api-washington-dc:
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=washington-dc
    ports: 
      - "8001:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app
  api-sao-paulo:
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=sao-paulo
    ports: 
      - "8002:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app
  api-mumbai:
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=mumbai
    ports: 
      - "8003:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app
  api-london:
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=london
    ports: 
      - "8004:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app
  
  api-sydney:
    build: ./products_service
    environment:
      - PORT=8000
      - NODE_ENV=development
      - NODE_APP_INSTANCE=sydney
    ports: 
      - "8005:8000"
    volumes:
      - ./products_service/:/app
      - /app/node_modules
      # - type: bind
      #   source: /Users/bhoyer/certs
      #   target: /app
  